IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[ASSET_CREATEBARCODE]') AND OBJECTPROPERTY(id,N'IsProcedure') = 1)
	DROP PROC [ASSET_CREATEBARCODE]
GO
/*
	创建条码
*/
CREATE PROC [ASSET_CREATEBARCODE]
@PREFIX NVARCHAR(50),		--前缀
@BARCODE NVARCHAR(50) OUTPUT
AS 
DECLARE @SN INT
EXEC [SYS_CREATESN_OUTPUT] @PREFIX,@SN OUTPUT 
DECLARE @SNLENGTH INT	--定义序列号长度
SET @SNLENGTH = 6
SET @BARCODE = @PREFIX+ RIGHT(N'00000000000000'+CONVERT(NVARCHAR,@SN),@SNLENGTH)

GO
