
CREATE VIEW V_STOCKHISTORY
AS
	SELECT S.F_ID,S.F_ENCODE,W.F_ID AS WHID,S.F_BLLCATEGORY,W.F_ENCODE WHCODE,W.F_FULLNAME WHNAME,C.F_ID POSID,C.F_ENCODE POSCODE,
		C.F_FULLNAME POSNAME,G.F_ID GOODSID,G.F_ENCODE GOODSCODE,S.F_BATCH,G.F_FULLNAME GOODSNAME,
		V.F_EnCode AS F_Vendor,V.F_FullName AS F_VENDORNAME,S.F_Contacts,S.F_TELEPHONE,S.F_ADDRESS,
		F_OperationNum,G.F_UNIT,G.F_SPECIFMODEL,F_Maker,S.F_VERIFY,S.F_VERIDATE,S.F_CREATORTIME,S.F_DESCRIPTION,S.F_SortCode
	FROM Sys_StockHistory AS S
	LEFT JOIN MST_WAREHOUSE AS W ON W.F_ID=S.F_WAREHOUSEID
	LEFT JOIN MST_CARGOPOSITION AS C ON C.F_ID=S.F_CARGOPOSITIONID
	LEFT JOIN MST_GOODS AS G ON G.F_ID=S.F_GOODSID
	LEFT JOIN Mst_Suppliers AS V ON V.F_Id=S.F_Vendor


GO