USE [KGM_WMS_DB]
GO

/****** Object:  StoredProcedure [dbo].[TEMPSCAN_SAVE]    Script Date: 2019/3/28 10:50:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




IF EXISTS (SELECT * FROM  SYS.PROCEDURES WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[TEMPSCAN_SAVE]'))
   DROP PROC [dbo].[TEMPSCAN_SAVE]
GO
CREATE PROC [dbo].[TEMPSCAN_SAVE]
@ORDERNO NVARCHAR(50),
@ORDERTYPE NVARCHAR(50),
@CWHCODE NVARCHAR(50),
@BARCODE NVARCHAR(500),
@CPOSCODE NVARCHAR(50),
@QTY DECIMAL(32,6),
@OPERUSER NVARCHAR(50),
@CMPOSCODE NVARCHAR(50),	--目标货位
@CMCHWCODE NVARCHAR(50),	--目标仓库
@BDEL BIT
AS
SET XACT_ABORT ON
BEGIN TRAN

DECLARE @CINVCODE NVARCHAR(50)
DECLARE @CBATCH NVARCHAR(50)
DECLARE @BODYID NVARCHAR(50)
DECLARE @STATUS INT

SET @CINVCODE = SUBSTRING(@BARCODE,0,CHARINDEX('|',@BARCODE))
SET @CBATCH = SUBSTRING(@BARCODE,LEN(@CINVCODE)+2,LEN(@BARCODE) - LEN(@CINVCODE))

IF NOT EXISTS(SELECT F_Id FROM Mst_Warehouse WHERE F_Id = @CWHCODE)
BEGIN
	SELECT N'仓库不存在,请确认单据内的仓库是否正确!'
	ROLLBACK
	RETURN
END 
DECLARE @POSID NVARCHAR(50)
SELECT @POSID = F_Id FROM Mst_CargoPosition WHERE F_WarehouseId = @CWHCODE AND F_Id = @CPOSCODE
IF ISNULL(@POSID,'') = '' and @ORDERTYPE!='CW'
BEGIN
	SELECT N'货位不存在或不属于仓库,请确认货位是否正确!'
	ROLLBACK
	RETURN
END 
 	
DECLARE @GOODID NVARCHAR(50)
DECLARE @GOODNAME NVARCHAR(50)
SELECT @GOODID = F_Id,@GOODNAME=F_FullName FROM Mst_Goods WHERE F_EnCode =  @CINVCODE
IF ISNULL(@GOODID,'') = ''
BEGIN
	SELECT N'商品不存在,请确认条码是否正确!'
	ROLLBACK
	RETURN
END

DECLARE @Id NVARCHAR(50)
IF @BDEL = 1  
BEGIN
	 UPDATE KGM_TEMPSCAN SET F_QTY = F_QTY - @QTY WHERE F_mainID = @ORDERNO AND F_ORDERTYPE = @ORDERTYPE AND F_BARCODE = @BARCODE AND F_PositionId = @CPOSCODE AND F_WarehouseId=@CWHCODE
	DELETE FROM KGM_TEMPSCAN WHERE F_mainID = @ORDERNO AND F_ORDERTYPE = @ORDERTYPE AND F_BARCODE = @BARCODE AND F_PositionId = @CPOSCODE  AND F_WarehouseId=@CWHCODE and F_qty<=0
END
ELSE
BEGIN
	--判断超量
	IF @ORDERTYPE = 'PI' 
	BEGIN 

	SELECT @Id= F_Id FROM  PI_Head WHERE F_EnCode=@ORDERNO
	IF  ISNULL(@Id,'')=''
	BEGIN
	SELECT N'单据号不存在，请输入正确的单据号'
			ROLLBACK
			RETURN
	END


	 IF EXISTS ( SELECT A.F_GoodsId 
			FROM (
				SELECT SUM(F_InStockNum) QTY,F_GoodsId
				FROM PI_Body 
				WHERE F_HId = (SELECT F_Id FROM PI_Head WHERE F_EnCode = @ORDERNO)
				AND F_GoodsId = @GOODID
				GROUP BY F_GoodsId
			) AS A
			LEFT JOIN (
				SELECT SUM(F_QTY) QTY,F_ProductId
				FROM KGM_TEMPSCAN
				WHERE F_mainID = @ORDERNO AND F_ORDERTYPE = @ORDERTYPE AND F_ProductId = @GOODID
				GROUP BY F_ProductId
			) AS B ON A.F_GoodsId = B.F_ProductId
			WHERE A.QTY < ISNULL(B.QTY,0) + @QTY )
		BEGIN
			SELECT N'扫描数量不允许超过单据数量'
			ROLLBACK
			RETURN
		END
	SELECT TOP 1 @BODYID=F_Id  FROM PI_Body  WHERE F_GoodsId=@GOODID AND F_WarehouseId=@CWHCODE AND F_CargoPositionId=@POSID
	END
		
	ELSE IF @ORDERTYPE = 'SO'
	BEGIN 
	SELECT @Id= F_Id,@STATUS=F_Status FROM  SO_Head WHERE F_EnCode=@ORDERNO
	IF  ISNULL(@Id,'')=''
	BEGIN
	SELECT N'单据号不存在，请输入正确的单据号'
			ROLLBACK
			RETURN
	END

	IF(@STATUS=0)
	BEGIN
	SELECT N'单据未审核，不允许扫描'
			ROLLBACK
			RETURN
	END

	IF(@STATUS>1)
	BEGIN
	SELECT N'单据已经完成，不允许扫描'
			ROLLBACK
			RETURN
	END
	
	IF EXISTS(SELECT F_Id FROM SO_Body WHERE F_HId= @Id AND F_WarehouseId=@CWHCODE AND F_CargoPositionId=@CPOSCODE AND F_GoodsId=@GOODID and F_Batch=@CBATCH)
	BEGIN
		SELECT N'请输入如正确的批次信息'
			ROLLBACK
			RETURN
	END


	IF EXISTS ( SELECT A.F_GoodsId 
			FROM (
				SELECT SUM(F_OutStockNum) QTY,F_GoodsId
				FROM So_Body 
				WHERE F_HId = (SELECT F_Id FROM SO_Head WHERE F_EnCode = @ORDERNO)
				AND F_GoodsId = @GOODID
				GROUP BY F_GoodsId
			) AS A
			LEFT JOIN (
				SELECT SUM(F_QTY) QTY,F_ProductId
				FROM KGM_TEMPSCAN
				WHERE F_mainID = @ORDERNO AND F_ORDERTYPE = @ORDERTYPE AND F_ProductId = @GOODID
				GROUP BY F_ProductId
			) AS B ON A.F_GoodsId = B.F_ProductId
			WHERE A.QTY < ISNULL(B.QTY,0) + @QTY )
		BEGIN
			SELECT N'扫描数量不允许超过单据数量'
			ROLLBACK
			RETURN
		END

		

	IF EXISTS ( SELECT A.F_GoodsId 
			FROM (
				SELECT SUM(F_Number) QTY,F_GoodsId,F_WarehouseId,F_CargoPositionId,F_Batch
				FROM Sys_Stock
				WHERE F_GoodsId = @GOODID AND F_WarehouseId = @CWHCODE AND F_CargoPositionId = @POSID AND F_Batch = @CBATCH
				GROUP BY F_GoodsId,F_WarehouseId,F_CargoPositionId,F_Batch
			) AS A
			LEFT JOIN (
				SELECT SUM(F_QTY) F_QTY,F_ProductId,F_WarehouseId,F_PositionId,F_CBATCH
				FROM KGM_TEMPSCAN AS A
				WHERE F_mainID = @ORDERNO AND F_ORDERTYPE = @ORDERTYPE AND F_ProductId = @GOODID
				  AND F_WarehouseId = @CWHCODE AND F_PositionId = @CPOSCODE AND F_CBATCH = @CBATCH
				GROUP BY F_ProductId,F_WarehouseId,F_PositionId,F_CBATCH
			) AS B ON A.F_GoodsId = B.F_ProductId AND A.F_WarehouseId = B.F_WarehouseId AND A.F_Batch = B.F_CBATCH
			WHERE A.QTY < B.F_QTY + @QTY )
		BEGIN
			SELECT N'扫描数量不允许超过库存数量'
			ROLLBACK
			RETURN
		END


     IF ISNULL(@CBATCH,'')=''
	 BEGIN
     SELECT TOP 1 @BODYID=F_Id  FROM SO_Body  WHERE F_GoodsId=@GOODID AND F_WarehouseId=@CWHCODE AND F_CargoPositionId=@POSID AND F_Batch IS NULL
	END
	ELSE
	BEGIN
	     SELECT TOP 1 @BODYID=F_Id  FROM SO_Body  WHERE F_GoodsId=@GOODID AND F_WarehouseId=@CWHCODE AND F_CargoPositionId=@POSID AND F_Batch=@CBATCH
	END
 

	END
	ELSE IF @ORDERTYPE='CW'
	BEGIN
 
		SELECT @Id= F_Id,@STATUS=F_Status  FROM  SO_StockMakeHead WHERE F_EnCode=@ORDERNO
	IF  ISNULL(@Id,'')=''
	BEGIN
	SELECT N'单据号不存在，请输入正确的单据号'
			ROLLBACK
			RETURN
	END

	IF(@STATUS=0)
	BEGIN
	SELECT N'单据未审核，不允许扫描'
			ROLLBACK
			RETURN
	END

		IF(@STATUS>1)
	BEGIN
	SELECT N'单据已经完成，不允许扫描'
			ROLLBACK
			RETURN
	END

	 



--写入临时表
 SELECT @Id=F_Id FROM SO_StockMakeHead WHERE F_EnCode=@ORDERNO; 

   IF ISNULL(@CBATCH,'')=''
	 BEGIN

SELECT @BODYID = F_ID FROM SO_StockMakeBody WHERE F_HId = @Id AND F_CargoPositionId = @CPOSCODE AND F_GoodsId = @GOODID AND F_Batch IS NULL
	END
	ELSE
	BEGIN
SELECT @BODYID = F_ID FROM SO_StockMakeBody WHERE F_HId = @Id AND F_CargoPositionId = @CPOSCODE AND F_GoodsId = @GOODID AND F_Batch=@CBATCH
	END
	END
	ELSE IF @ORDERTYPE='MP'
	BEGIN
--DECLARE @GETWARId NVARCHAR(50)
--DECLARE @GETPOId NVARCHAR(50)
--SELECT @GETWARId = F_Id FROM Mst_Warehouse WHERE F_Id = @CMCHWCODE
--IF ISNULL(@GETWARId,'') = ''
--BEGIN
--	SELECT N'目标仓库不存在，请输入正确的仓库编码!'
--	ROLLBACK
--	RETURN
--END 
 	
--SELECT @GETPOId = F_Id FROM Mst_CargoPosition WHERE F_WarehouseId = @CMCHWCODE and F_Id=@CMPOSCODE
--IF ISNULL(@GETPOId,'') = ''  
--BEGIN
--	SELECT N'目标货位不存在，请输入正确的仓库编码!'
--	ROLLBACK
--	RETURN
--END 	
DECLARE @MQTY INT
SELECT  @MQTY=F_Number FROM Sys_Stock WHERE F_GoodsId=@GOODID AND F_WarehouseId=@CWHCODE AND  F_CargoPositionId=@CPOSCODE AND F_Batch =@CBATCH
IF  @MQTY IS NULL OR @MQTY=''
BEGIN
SELECT '在库存中未找到批次为'+@CBATCH+'的商品'+@GOODNAME 
ROLLBACK
RETURN
END


IF(@MQTY<@QTY)
BEGIN
SELECT '转移商品在货位上的库存不足，请重新输入' 
ROLLBACK
RETURN
END

	END
	IF EXISTS(SELECT F_ID FROM KGM_TEMPSCAN WHERE F_mainID = @ORDERNO AND F_ORDERTYPE = @ORDERTYPE AND F_BARCODE = @BARCODE AND F_PositionId = @CPOSCODE)
	BEGIN
		UPDATE KGM_TEMPSCAN SET F_QTY = F_QTY + @QTY WHERE F_mainID = @ORDERNO AND F_ORDERTYPE = @ORDERTYPE AND F_BARCODE = @BARCODE AND F_PositionId = @CPOSCODE
	END
	ELSE
	BEGIN

INSERT INTO KGM_TEMPSCAN (F_ID,F_CMPOSCODE,F_CMCHWCODE,F_autoID,F_mainID,F_ORDERTYPE,F_BARCODE,F_ProductId,F_ProductCode,F_ProductName,F_WarehouseId,F_PositionId,F_CBATCH,F_QTY,F_OPERUSER,F_operDate)
		SELECT NEWID(),@CMPOSCODE,@CMCHWCODE,@BODYID,@ORDERNO,@ORDERTYPE,@BARCODE,F_Id,F_EnCode,F_FullName,@CWHCODE,@CPOSCODE,@CBATCH, @QTY,@OPERUSER,GETDATE()
		FROM Mst_Goods
		WHERE F_Id = @GOODID
END
	END
SELECT ''
COMMIT TRAN

GO


