USE [KGM_WMS_DB]
GO

/****** Object:  StoredProcedure [dbo].[TEMPSCAN_DELETE]    Script Date: 2019/3/28 10:42:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


/*
	删除扫描记录
*/
IF EXISTS(SELECT  * FROM SYS.PROCEDURES WHERE  OBJECT_ID = OBJECT_ID(N'[dbo].[TEMPSCAN_DELETE]'))
   DROP PROC [dbo].[TEMPSCAN_DELETE]
GO
CREATE PROC [dbo].[TEMPSCAN_DELETE]
@ORDERNO NVARCHAR(50),		--单据号
@ORDERTYPE NVARCHAR(50),	--单据类型
@CWHCODE NVARCHAR(50),		--仓库编码
@CPOSCODE NVARCHAR(50),		--货位码
@CINVSKU NVARCHAR(50),		--SKU
@BOXNO NVARCHAR(50),		--箱号
@QTY INT					--数量 
AS

DECLARE @PACKBOX NVARCHAR(50)
SET @PACKBOX = ''
DECLARE @MYTYPE NVARCHAR(50)
SET @MYTYPE = @ORDERTYPE
SET @ORDERTYPE = SUBSTRING(@MYTYPE,1,2)

IF @ORDERTYPE = 'SO' AND SUBSTRING(@ORDERNO,1,2) = 'DP'
BEGIN
	SET @PACKBOX = @ORDERNO + SUBSTRING(@MYTYPE,4,3)
	  
	SELECT F_ID,F_QTY,F_INSERTTIME F_OPERDATE INTO #TEMP_DELETE_SP
	FROM SO_PACKAGE 
	WHERE  F_ORDERNO = @ORDERNO AND F_ProductId = @CINVSKU AND F_BOXNO = @PACKBOX

	DECLARE @ID NVARCHAR(50)
	DECLARE @TEMPQTY INT
	
	WHILE EXISTS(SELECT F_ID FROM #TEMP_DELETE_SP)
	BEGIN
		SELECT TOP 1 @ID = F_ID,@TEMPQTY = F_QTY FROM #TEMP_DELETE_SP ORDER BY F_OPERDATE DESC 
		IF @TEMPQTY >= @QTY
		BEGIN
			UPDATE SO_PACKAGE SET F_QTY = F_QTY - @QTY WHERE F_ID = @ID 
			BREAK
		END 
		ELSE
		BEGIN
			UPDATE SO_PACKAGE SET F_QTY = 0 WHERE F_ID = @ID 
			SET @QTY = @QTY - @TEMPQTY
		END

		DELETE FROM #TEMP_DELETE_SP WHERE F_ID = @ID
	END
	--删除最后一笔扫描记录的数量
	DELETE FROM SO_PACKAGE 
	WHERE  F_ORDERNO = @ORDERNO AND F_PRODUCTID = @CINVSKU AND f_BOXNO = @PACKBOX AND f_QTY <= 0 
END
ELSE
BEGIN
	IF ISNULL(@CINVSKU,'') = ''
	BEGIN 
		DELETE FROM KGM_TEMPSCAN 
		WHERE F_MAINID = @ORDERNO AND F_ORDERTYPE = @ORDERTYPE AND F_BOXNO = @BOXNO 
			AND F_WAREHOUSEID = @CWHCODE AND F_POSITIONID = @CPOSCODE
	END
	ELSE
	BEGIN
		SELECT F_ID,F_QTY,F_OPERDATE INTO #TEMP_DELETE
		FROM KGM_TEMPSCAN 
		WHERE  f_MAINID = @ORDERNO AND f_ORDERTYPE = @ORDERTYPE AND F_PRODUCTID = @CINVSKU 
			AND F_WAREHOUSEID = @CWHCODE AND F_POSITIONID = @CPOSCODE 
			 	
		WHILE EXISTS(SELECT F_ID FROM #TEMP_DELETE)
		BEGIN
			SELECT TOP 1 @ID = F_ID,@TEMPQTY = F_QTY FROM #TEMP_DELETE ORDER BY F_OPERDATE DESC 
			IF @TEMPQTY >= @QTY
			BEGIN
				UPDATE KGM_TEMPSCAN SET F_QTY =F_QTY - @QTY WHERE F_ID = @ID 
				BREAK
			END 
			ELSE
			BEGIN
				UPDATE KGM_TEMPSCAN SET F_QTY = 0 WHERE F_ID = @ID 
				SET @QTY = @QTY - @TEMPQTY
			END

			DELETE FROM #TEMP_DELETE WHERE F_ID = @ID
		END
		--删除最后一笔扫描记录的数量
		DELETE FROM KGM_TEMPSCAN 
		WHERE  F_MAINID = @ORDERNO AND F_ORDERTYPE = @ORDERTYPE AND F_PRODUCTID = @CINVSKU 
			AND F_WAREHOUSEID = @CWHCODE AND F_POSITIONID = @CPOSCODE AND F_QTY <= 0
	END
END



GO


