USE [KGM_WMS_DB]
GO

/****** Object:  StoredProcedure [dbo].[TEMPSCAN_GETDIFFLIST]    Script Date: 2019/3/28 10:50:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
IF EXISTS (SELECT * FROM  SYS.PROCEDURES WHERE OBJECT_ID = OBJECT_ID(N'[dbo].[TEMPSCAN_GETDIFFLIST]'))
   DROP PROC [dbo].[TEMPSCAN_GETDIFFLIST]
GO
CREATE PROC [dbo].[TEMPSCAN_GETDIFFLIST]
@ORDERNO NVARCHAR(50),		--单据号
@ORDERTYPE NVARCHAR(50)		--单据类型
AS 
SET XACT_ABORT ON
BEGIN TRAN
DECLARE @ISBOX INT 
SET @ISBOX = 0

CREATE TABLE #TEMP_SOURCE
(
	CINVSKU NVARCHAR(50) PRIMARY KEY,	--SKU
	QTY INT								--单据数量
)
DECLARE @ID NVARCHAR(50)
IF @ORDERTYPE = 'PI'	--产品到货
BEGIN
	IF EXISTS(SELECT F_ID FROM PI_HEAD WHERE F_EnCode = @ORDERNO ) --AND ORDERTYPE = 0)
	BEGIN
		--散件
		INSERT INTO #TEMP_SOURCE(CINVSKU,QTY)
		SELECT F_GoodsId,SUM(F_InStockNum)
		FROM PI_Body
		WHERE F_OrderNo = @ORDERNO
		GROUP BY F_GoodsId
	END
END
ELSE IF @ORDERTYPE = 'SO'	--产品上架
BEGIN
	SELECT @ID = F_ID FROM SO_Head WHERE F_EnCode = @ORDERNO
	IF EXISTS(SELECT F_ID FROM SO_Head WHERE F_EnCode = @ORDERNO) -- AND ORDERTYPE = 0)
	BEGIN
		--散件
		INSERT INTO #TEMP_SOURCE(CINVSKU,QTY)
		SELECT F_GoodsId,SUM(F_OutStockNum)
		FROM SO_Body
		WHERE F_HId = @ID

		GROUP BY F_GoodsId

 
	END
	
END

ELSE IF @ORDERTYPE = 'CW'	--产品盘点
BEGIN
	SELECT @ID = F_ID FROM SO_StockMakeHead WHERE F_EnCode = @ORDERNO
	
	IF EXISTS(SELECT F_ID FROM SO_StockMakeHead WHERE F_EnCode = @ORDERNO) -- AND ORDERTYPE = 0)
	BEGIN
		--散件
		INSERT INTO #TEMP_SOURCE(CINVSKU,QTY)
		SELECT F_GoodsId,SUM(F_Number)
		FROM SO_StockMakeBody
		WHERE F_HId = @ID

		GROUP BY F_GoodsId
	END
	
END

BEGIN
		SELECT I.F_EnCode GoodCode,S.QTY,ISNULL(A.QTY,0) DONEQTY,ISNULL(S.QTY,0) - ISNULL(A.QTY,0) CYQTY
		FROM #TEMP_SOURCE AS S
		LEFT JOIN (
			SELECT F_ProductId,SUM(F_qty) QTY 
			FROM KGM_TEMPSCAN  
			WHERE F_MAINID = @ORDERNO AND F_ORDERTYPE = @ORDERTYPE
			GROUP BY F_ProductId
		)AS A ON S.CINVSKU = A.F_ProductId
		LEFT JOIN Mst_Goods AS I ON S.CINVSKU = I.F_Id
	    LEFT JOIN Mst_CargoPosition AS C ON C.F_Id = A.F_ProductId
	END

COMMIT TRAN
GO


