USE [KGM_WMS_DB]
GO

/****** Object:  StoredProcedure [dbo].[TEMPSCAN_FINISH_CW]    Script Date: 2019/3/28 10:46:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/*
	库存盘点扫描完成
*/
IF EXISTS (select * from sys.procedures where object_id = OBJECT_ID(N'[dbo].[[TEMPSCAN_FINISH_CW]]'))
   drop proc [dbo].[TEMPSCAN_FINISH_CW]
go
CREATE PROC [dbo].[TEMPSCAN_FINISH_CW]
@ORDERNO NVARCHAR(50),		--单据号
@ORDERTYPE NVARCHAR(50),	--单据类型
@RESULT INT OUTPUT,			--返回状态
@MSG NVARCHAR(4000) OUTPUT	--返回信息
AS  



--判断单据状态
EXEC [CW_VALIDATE_STATUS] @ORDERNO,@MSG OUTPUT
IF ISNULL(@MSG,'') <> ''
BEGIN
	SET @RESULT = 0
	RETURN
END 

 

----差异表
--CREATE TABLE #TEMP_CYDATA
--(
--	CINVADDCODE NVARCHAR(50),
--	CINVNAME NVARCHAR(50),
--	CINVSKU NVARCHAR(50),
--	QTY INT,
--	DONEQTY INT,
--	CYQTY INT
--)

----获取差异信息
--INSERT INTO #TEMP_CYDATA(CINVADDCODE,CINVNAME,CINVSKU,QTY,DONEQTY,CYQTY)
--EXEC [TEMPSCAN_GETDIFFLIST] @ORDERNO,@ORDERTYPE 

--IF EXISTS(SELECT CINVSKU FROM #TEMP_CYDATA WHERE CYQTY <> 0)
--BEGIN 
--	--锁定主表
--	--UPDATE PU_MAIN SET ISLOCK = 1 WHERE ORDERNO = @ORDERNO 
--	----锁定扫描表 status = 1
--	--UPDATE KGM_TEMPSCAN SET [STATUS] = 1 WHERE MAINID = @ORDERNO AND ORDERTYPE = @ORDERTYPE
--	SET @RESULT=0
--	SET @MSG = N'当前扫描记录存在差异,不允许完成!' 
--	RETURN
--END
--ELSE 
--BEGIN

CREATE TABLE #TEMP_PDDATA
(
	PRODUCTID NVARCHAR(50),
	QTY INT,
    WAREHOUSEID NVARCHAR(50),
	POSITIONID NVARCHAR(50),
	BATCH NVARCHAR(50),
)
INSERT INTO #TEMP_PDDATA
SELECT F_ProductId AS PRODUCTID,F_qty AS QTY,F_WarehouseId AS WAREHOUSEID,F_PositionId AS POSITIONID,F_cbatch AS BATCH 
FROM KGM_TEMPSCAN 
WHERE F_mainID=@ORDERNO 
and F_orderType=@ORDERTYPE

--更新库存
 WHILE EXISTS(SELECT PRODUCTID FROM #TEMP_PDDATA)
 BEGIN
 DECLARE @GOODSID NVARCHAR(50)
 DECLARE @WAREHOUSEID NVARCHAR(50)
 DECLARE @POSITIONID NVARCHAR(50)
 DECLARE @BATCH NVARCHAR(50)
 DECLARE @QTY FLOAT

	 SELECT top 1 @GOODSID= PRODUCTID,@QTY=QTY, @WAREHOUSEID=WAREHOUSEID,@POSITIONID=POSITIONID,@BATCH=BATCH FROM #TEMP_PDDATA
	 --如果存在则修改库存，否则添加库存
	 IF EXISTS(SELECT * FROM Sys_Stock  WHERE F_GoodsId=@GOODSID AND F_WarehouseId=@WAREHOUSEID AND F_CargoPositionId=@POSITIONID AND F_Batch=@BATCH)
	 BEGIN


		 UPDATE Sys_Stock set  F_Number=@QTY WHERE F_GoodsId=@GOODSID AND F_WarehouseId=@WAREHOUSEID AND F_CargoPositionId=@POSITIONID AND F_Batch=@BATCH
		 END
		 ELSE
		 BEGIN

		 INSERT INTO Sys_Stock(F_ID,F_BATCH,F_WAREHOUSEID,F_GOODSID,F_Number,F_CargoPositionId,F_SpecifModel,F_Unit,F_SellingPrice,F_WarehouseName,F_CargoPositionName)
		 SELECT NEWID(),@BATCH,W.F_ID,@GOODSID,@QTY,@POSITIONID,G.F_SpecifModel,G.F_Unit,G.F_SellingPrice ,W.F_FULLNAME,C.F_FULLNAME FROM Mst_Goods G 
		 LEFT JOIN Mst_Warehouse  W ON W.F_Id=@WAREHOUSEID
		 Left JOIN Mst_CargoPosition C ON C.F_Id=@POSITIONID
		 WHERE G.F_Id=@GOODSID
 
	 END
		--写入出盘点履历
	INSERT INTO Sys_StockMaskHistory(F_Id,F_EnCode,F_GoodsId,F_GoodsCode,F_GoodsName,F_WarehouseId,F_WarehouseName,F_CargoPositionId,F_CargoPositionName,F_Batch,F_Number,F_DiffNumber,F_RealNumber,F_SellingPrice,F_Unit,F_Operator,F_Date)
	SELECT  newid(),h.F_EnCode,g.F_Id,g.F_EnCode,g.F_FullName,w.F_Id,w.F_FullName,c.F_Id,c.F_FullName,k.F_cbatch,b.F_Number,ABS(b.F_Number-b.F_RealNumber),b.F_RealNumber,g.F_SellingPrice,G.F_Unit,h.F_Operator,h.F_date
	FROM KGM_TEMPSCAN K
	LEFT JOIN SO_StockMakeHead H ON  K.F_mainID=H.F_EnCode
    LEFT JOIN SO_StockMakeBody B ON  b.F_HId=H.F_Id
	LEFT JOIN Mst_Warehouse W ON K.F_WarehouseId=W.F_Id
	LEFT JOIN Mst_CargoPosition C ON C.F_Id=K.F_PositionId
	LEFT JOIN Mst_Goods G ON K.F_ProductId=G.F_Id
	WHERE K.F_mainID = @ORDERNO AND K.F_orderType = @ORDERTYPE 


	DELETE FROM #TEMP_PDDATA WHERE PRODUCTID=@GOODSID AND QTY=@QTY AND WAREHOUSEID=@WAREHOUSEID AND POSITIONID=@POSITIONID AND BATCH=@BATCH
 END
 --END
 --DELETE FROM KGM_TEMPSCAN WHERE F_mainID=@ORDERNO AND F_orderType=@ORDERTYPE
		--删除0库存
DELETE FROM Sys_Stock WHERE F_Number <= 0
DELETE FROM KGM_TEMPSCAN WHERE F_mainID=@ORDERNO AND F_orderType=@ORDERTYPE
UPDATE SO_StockMakeHead SET F_STATUS = 2 WHERE F_EnCode = @ORDERNO

SET @RESULT = 1
SET @MSG = ''  



GO


