IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[V_PADDINGSTOCK]') AND OBJECTPROPERTY(id,N'IsView') = 1)
	DROP VIEW V_PADDINGSTOCK
GO  
/*
	‘§’ºø‚¥Ê ”Õº
*/ 
CREATE VIEW V_PADDINGSTOCK WITH SCHEMABINDING
AS
SELECT CINVSKU,CPOSCODE,CWHCODE,BARCODE SN,CCUSCODE,SUM(QTY) QTY,PROPERTY,BOXNO
FROM dbo.SM_PACKINGSTOCK 
GROUP BY CINVSKU,CPOSCODE,CWHCODE,BARCODE,CCUSCODE,PROPERTY,BOXNO
UNION
SELECT CINVCODE CINVSKU,CPOSCODE,CWHCODE,SN,CCUSCODE,SUM(QTY) QTY,PROPERTY,BOXNO
FROM dbo.KGM_TEMPSCAN
WHERE ORDERTYPE = 'MP'
GROUP BY CINVCODE,CPOSCODE,CWHCODE,SN,CCUSCODE,PROPERTY,BOXNO
GO


 