IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[V_STOCK]') AND OBJECTPROPERTY(id,N'IsView') = 1)
	DROP VIEW V_STOCK
GO  
/*
	ø‚¥Ê ”Õº
*/ 
CREATE VIEW V_STOCK WITH SCHEMABINDING
AS
SELECT A.F_ID,A.BARCODE,A.CINVSKU,I.CINVADDCODE,I.CINVNAME,I.CINVDEFINE1,I.CINVDEFINE2,I.CINVDEFINE3,I.CINVDEFINE4,
I.CINVDEFINE5,I.CINVDEFINE6,I.CINVDEFINE7,I.CINVDEFINE8,I.CINVDEFINE9,I.CINVDEFINE10,I.CINVDEFINE11,I.CINVDEFINE12,
I.CINVDEFINE13,I.CINVDEFINE14,I.CINVDEFINE15,I.CINVDEFINE16,I.CINVDEFINE17,I.CINVDEFINE18,I.CINVDEFINE19,I.CINVDEFINE20,
A.QTY,A.BOXNO,A.BSTOPFLAG,A.cPosCode,A.INDATE,C.CCUSADDCODE,C.CCUSNAME,IDE.F_ITEMCODE PROPERTYCODE,
IDE.F_ITEMNAME PROPERTYNAME,W.CWHADDCODE,W.CWHNAME,A.CCUSCODE,A.CWHCODE, COUNT_BIG(*) CC,bPosProp
FROM dbo.SM_STOCK A
INNER JOIN dbo.MST_WAREHOUSE AS W ON A.CWHCODE = W.CWHCODE
INNER JOIN dbo.MST_INVENTORY AS I ON A.CINVSKU = I.CINVSKU 
INNER JOIN dbo.MST_CUSTOMER AS C ON A.CCUSCODE = C.CCUSCODE
INNER JOIN dbo.MST_POSITION AS P ON A.cPosCode = P.CPOSCODE AND A.CWHCODE = P.CWHCODE
INNER JOIN (
	SELECT F_Id,F_ItemCode,F_ItemName FROM dbo.Sys_ItemsDetail WHERE F_ItemId = '0bc05e2b-0edd-49d3-bd25-e1eee8583545'
	UNION
	SELECT F_Id,CCUSADDCODE,CCUSNAME FROM dbo.MST_CUSTOMER
) AS IDE ON A.PROPERTY = IDE.F_ID
GROUP BY A.F_ID,A.BARCODE,A.CINVSKU,I.CINVADDCODE,I.CINVNAME,I.CINVDEFINE1,I.CINVDEFINE2,I.CINVDEFINE3,I.CINVDEFINE4,
I.CINVDEFINE5,I.CINVDEFINE6,I.CINVDEFINE7,I.CINVDEFINE8,I.CINVDEFINE9,I.CINVDEFINE10,I.CINVDEFINE11,I.CINVDEFINE12,
I.CINVDEFINE13,I.CINVDEFINE14,I.CINVDEFINE15,I.CINVDEFINE16,I.CINVDEFINE17,I.CINVDEFINE18,I.CINVDEFINE19,I.CINVDEFINE20,
A.QTY,A.BOXNO,A.BSTOPFLAG,A.cPosCode,A.INDATE,C.CCUSADDCODE,C.CCUSNAME,
IDE.F_ITEMCODE,IDE.F_ITEMNAME,W.CWHADDCODE,W.CWHNAME,A.CCUSCODE,A.CWHCODE,bPosProp
GO

--CREATE UNIQUE CLUSTERED INDEX PK_VSTOCK ON V_STOCK(F_ID)
--CREATE INDEX IDX_CCUSCODE_VSTOCK ON V_STOCK(CCUSCODE)
--CREATE INDEX IDX_CWHCODE_VSTOCK ON V_STOCK(CWHCODE)
--CREATE INDEX IDX_BARCODE_VSTOCK ON V_STOCK(BARCODE)
--CREATE INDEX IDX_BOXNO_VSTOCK ON V_STOCK(BOXNO)
--CREATE INDEX IDX_INSTOCKDATE_VSTOCK ON V_STOCK(INDATE)
GO

 