IF EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[SYS_GENERATE_SN]') AND OBJECTPROPERTY(ID,N'ISPROCEDURE') = 1)
	DROP PROC [SYS_GENERATE_SN]
GO
/*
	创建流水号
*/
CREATE PROC [SYS_GENERATE_SN]
@PREFIX NVARCHAR(50),		--前缀
@SNLENGTH INT = 5,				--序列号长度 默认5位
@BPREFIX BIT = 1,			--是否需要拼接前缀 默认需要
@DELDAY INT = 30			--清除序列号时间 默认30天
AS
DECLARE @SNNO INT	--当前序列号 
SELECT @SNNO = F_SN + 1 FROM Sys_Serial WHERE F_Prefix = @PREFIX
IF ISNULL(@SNNO,-1) = -1
BEGIN
	--新增 
	SET @SNNO = 1
	INSERT INTO Sys_Serial(F_Prefix,F_SN) VALUES(@PREFIX,@SNNO)
END
ELSE
BEGIN
	--更新
	UPDATE Sys_Serial SET F_SN = @SNNO,F_LastModifyTime = GETDATE() WHERE F_Prefix = @PREFIX
END

IF @BPREFIX = 1
BEGIN	
	SELECT @PREFIX + RIGHT('00000000000000'+CAST(ISNULL(@SNNO,1) AS NVARCHAR),@SNLENGTH)
END
ELSE
BEGIN
	SELECT RIGHT('00000000000000'+CAST(ISNULL(@SNNO,1) AS NVARCHAR),@SNLENGTH)
END

IF @DELDAY > 0
BEGIN 
	--清除不使用的流水种子
	DELETE FROM Sys_Serial WHERE F_Prefix = @PREFIX AND DATEDIFF(DAY,F_LastModifyTime,GETDATE()) >= @DELDAY
END

GO

 