IF EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[SYS_SAVELOG]') AND OBJECTPROPERTY(ID,N'ISPROCEDURE') = 1)
	DROP PROC [SYS_SAVELOG]
GO
/*
	记录日志信息
*/
CREATE PROC[SYS_SAVELOG]
@ACCOUNT NVARCHAR(50),		--登录用户
@NICKNAME NVARCHAR(50),		--用户姓名
@LOGTYPE NVARCHAR(50),		--日志类型
@MODULEID NVARCHAR(50),		--模块ID
@MODULENAME NVARCHAR(100),	--模块名
@IPADDRESS NVARCHAR(50),	--IP地址
@IPADDRESSNAME NVARCHAR(50),--IP地址对应名
@RESULT BIT,				--成功失败标识 0 失败 1 成功
@DESCRIPTION NVARCHAR(500)	--错误描述
AS 
BEGIN TRY
	--声明变量，存放当前已开启的事务数
	DECLARE @EXIST_TRANCOUNT INT
	SELECT @EXIST_TRANCOUNT = @@TRANCOUNT

	IF @EXIST_TRANCOUNT > 0
		SAVE TRANSACTION TRAN_PROC   --创建事务保存点
	ELSE
		BEGIN TRANSACTION TRAN_PROC  --开启新事务
 
	/*
		存储过程业务处理代码 
	*/
	INSERT INTO Sys_Log(F_Id,F_Date,F_Account,F_NickName,F_Type,F_IPAddress,F_IPAddressName,F_ModuleId,F_ModuleName,F_Result,F_Description,F_CreatorTime,F_CreatorUserId)
	VALUES(NEWID(),GETDATE(),@ACCOUNT,@NICKNAME,@LOGTYPE,@IPADDRESS,@IPADDRESSNAME,@MODULEID,@MODULENAME,@RESULT,@DESCRIPTION,GETDATE(),@ACCOUNT)
 
	IF @EXIST_TRANCOUNT = 0
		--提交事务
		COMMIT TRAN TRAN_PROC
	SELECT 1,N''
END TRY
BEGIN CATCH
	ROLLBACK TRANSACTION TRAN_PROC 
	SELECT 0,ERROR_MESSAGE()
END CATCH
 
