
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[ASSET_VERIFYLIST]') AND OBJECTPROPERTY(id,N'IsProcedure') = 1)
	DROP PROC [ASSET_VERIFYLIST]
GO
/*
	审核单据
*/
CREATE PROC ASSET_VERIFYLIST
@ORDERID NVARCHAR(50),	--单据Id
@ORDERNO NVARCHAR(50),	--单据号
@ORDERTYPE NVARCHAR(50), --单据类型
@USER NVARCHAR(50),		--审核人
@COMPID NVARCHAR(50)	--公司Id
AS
SET XACT_ABORT ON
BEGIN TRAN
DECLARE @COMPCODE NVARCHAR(50) 
SELECT @COMPCODE = F_EnCode FROM Sys_Organize WHERE F_Id = @COMPID

IF @ORDERTYPE = '资产登记'
BEGIN
	EXEC ASSET_VERIFYLIST_ZCDJ @ORDERID,@ORDERNO,@USER,@COMPCODE
END
ELSE IF @ORDERTYPE = '资产领用' OR @ORDERTYPE = '资产变更' OR @ORDERTYPE = '资产借用' OR @ORDERTYPE = '资产归还' 
	OR @ORDERTYPE = '资产维修' OR @ORDERTYPE = '资产处理'
BEGIN
	EXEC ASSET_VERIFYLIST_ZCZY @ORDERID,@ORDERNO,@ORDERTYPE,@USER,@COMPCODE
END
ELSE IF @ORDERTYPE = '资产调出' OR @ORDERTYPE = '资产调入' 
BEGIN
	EXEC ASSET_VERIFYLIST_ZCDB @ORDERID,@ORDERNO,@ORDERTYPE,@USER,@COMPCODE
END
ELSE IF @ORDERTYPE = '资产盘点' 
BEGIN
	EXEC ASSET_VERIFYLIST_ZCPD @ORDERID,@ORDERNO,@USER,@COMPCODE
END

COMMIT TRAN
GO 